name: "zoraauth"
version: "0.2.0"
usage: "Handle Device Authorization Workflow on behalf of Zora Operator"
description: "Handle Device Authorization Workflow on behalf of Zora Operator"
command: "$HELM_PLUGIN_DIR/bin/zoraauth"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
