name: build-test

on:
  push:
    branches:
      - "main"
      - "release-**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Run Test
        run: make test
      - name: Build
        run: make build
